FROM node:slim AS builder

WORKDIR /app

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

ARG DATABASE_HOST
ENV DATABASE_HOST=${DATABASE_HOST}

ARG DATABASE_PORT
ENV DATABASE_PORT=${DATABASE_PORT}

ARG DATABASE_USER
ENV DATABASE_USER=${DATABASE_USER}

ARG DATABASE_PASSWORD
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}

ARG DATABASE_NAME
ENV DATABASE_NAME=${DATABASE_NAME}


RUN apk update
RUN npm install pnpm -g

COPY package*.json .
COPY pnpm-lock.yaml .
RUN pnpm install

COPY . .
RUN pnpm build



FROM node:lts-alpine AS production
WORKDIR /app
COPY --from=builder /app .

EXPOSE 3000

ENTRYPOINT [ "node","dist/src/main" ]


